### ISSUE TITLE
UsdView QT Issues

### ISSUE THREAD

**Issue by jonassorgenfrei** [PixarAnimationStudios/USD#1970]
### Description of Issue
Hey,

i build the current state of the release branche and getting the following error when opening the usdview.
I build usd on windows and used python 3.7.

```
Traceback (most recent call last):
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\bin\usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\__init__.py", line 79, in Run
    self.__LaunchProcess(arg_parse_result)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\__init__.py", line 324, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\__init__.py", line 314, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\appController.py", line 419, in __init__
    self._ui.setupUi(self._mainWindow)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\mainWindowUI.py", line 1150, in setupUi
    self.retranslateUi(MainWindow)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\mainWindowUI.py", line 1208, in retranslateUi
    self.metadataView.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Field Name", None, -1))
AttributeError: 'NoneType' object has no attribute 'setText'
```

```
Traceback (most recent call last):
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\appController.py", line 2845, in _propSelectionChanged
    self._updatePropertyInspector()
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\appController.py", line 2882, in _updatePropertyInspector
    self._updateLayerStackView(obj)
  File "D:\Bibliotheken\usd\usd-pixarAnimationStudios\build\install\lib\python\pxr\Usdviewq\appController.py", line 4128, in _updateLayerStackView
    tableWidget.horizontalHeaderItem(1).setText('Path')
AttributeError: 'NoneType' object has no attribute 'setText'
```

Feels like it's not completly PySide2 conform (?).

Is this a common/known issue or is this just for me?

### System Information (OS, Hardware)
Windows 10
Python 3.7 
x64

**Comment by spiffmon** [comment]
I don't recall ever seeing anything like that reported, @jonassorgenfrei , and don't have any immediate thoughts, though others might.

**Comment by sunyab** [comment]
This appears to be a duplicate of #914, which was a PySide2 bug that was resolved updating to a newer version. Could you check your PySide2 version and see if upgrading to a newer version resolves the issue?

**Comment by jonassorgenfrei** [comment]
Hey @sunyab thanks for the answer,
yes after updating from PySide 5.13.... to 5.15.2.1 and recompiling usd it works now. 
Sorry for the duplicated ticket

**Comment by sunyab** [comment]
No problem, glad it all worked out!
