### ISSUE TITLE
State file not found, a new one will be created.

### ISSUE THREAD

**Issue by HugoDepping** [PixarAnimationStudios/USD#2407]
### Description of Issue
TypeError when trying to open a usda file with usdview. anyone with similair issue? i would like to follow the pixar usd tutorials

### Steps to Reproduce
1. Download https://github.com/PixarAnimationStudios/USD/blob/release/VERSIONS.md
2. in x64 Native Tools Command Prompt for VS 2019 type: python "your/path/to/"Build_usd.py "C:\USD"
3. Result build works
4. in x64 Native Tools Command Prompt for VS 2019 type: usdview "your/path/to/"HelloWorld.usda

### ERROR
C:\Projects\USD-release\USD-release\extras\usd\tutorials\helloWorld>usdview HelloWorld.usda
State file not found, a new one will be created.
Traceback (most recent call last):
  File "C:\USD\bin\usdview", line 35, in <module>
    Usdviewq.Launcher().Run()
  File "C:\USD\lib\python\pxr\Usdviewq\__init__.py", line 86, in Run
    self.__LaunchProcess(arg_parse_result)
  File "C:\USD\lib\python\pxr\Usdviewq\__init__.py", line 396, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "C:\USD\lib\python\pxr\Usdviewq\__init__.py", line 386, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "C:\USD\lib\python\pxr\Usdviewq\appController.py", line 410, in __init__
    self._dataModel = UsdviewDataModel(self._makeTimer, self._configManager.settings)
  File "C:\USD\lib\python\pxr\Usdviewq\appController.py", line 128, in __init__
    self._viewSettingsDataModel = ViewSettingsDataModel(self, settings)
  File "C:\USD\lib\python\pxr\Usdviewq\viewSettingsDataModel.py", line 136, in __init__
    QtCore.QObject.__init__(self)
TypeError: __init__() missing 2 required positional arguments: 'parent' and 'name'

**Comment by TanJeremy** [comment]
Hi, I had this issue monday,
to complement your submit, I made the build with python 3.10.6, i don't know about you, but as i'm not sure python 3.10 is supported, i didn't adress this issue.
If you want i found a workaroud:
in C:\USD\lib\python\pxr\Usdviewq\viewSettingsDataModel.py", line 136
you can inverse the inheritance order and invert the init order:

```python
class ViewSettingsDataModel(StateSource, QtCore.QObject):

...


    def __init__(self, rootDataModel, parent):
        StateSource.__init__(self, parent, "model")
        QtCore.QObject.__init__(self)
```
it appear that `QtCore.QObject.__init__()` initiate `StateSource.__init__()` without argument

**Comment by HugoDepping** [comment]
Thanks @TanJeremy this works! I used python 3.8.10

**Comment by sunyab** [comment]
Hi all, just wanted to note that this is a known issue related to a change in behavior in PySide 6.5.0. A PR with a fix for this issue (which is the same fix as @TanJeremy posted) is here: https://github.com/PixarAnimationStudios/USD/pull/2392

An alternate workaround is to use an older version of PySide.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8272

**Comment by beersandrew** [comment]
Thanks all for logging and posting about workarounds. Really appreciate it

**Comment by FlorianZ** [comment]
Closing this given that it's a known issue and we have a PR that promises to fix this.
