### ISSUE TITLE
build break with boost 1.64

### ISSUE THREAD

**Issue by waywardmonkeys** [PixarAnimationStudios/USD#248]
### Description of Issue

When I build with boost 1.64, I get this error:

```
../pxr/usd/lib/usd/clip.cpp:572:29: error: no viable overloaded '='
        clipSet->anchorInfo = {
        ~~~~~~~~~~~~~~~~~~~ ^ ~
/usr/local/include/boost/optional/optional.hpp:943:15: note: candidate function not viable: cannot convert initializer list argument to 'const boost::optional<pxrInternal_v0_7__pxrReserved__::(anonymous namespace)::_ClipSet::_AnchorInfo>'
    optional& operator= ( optional const& rhs )
              ^
/usr/local/include/boost/optional/optional.hpp:951:15: note: candidate function not viable: cannot convert initializer list argument to 'boost::optional<pxrInternal_v0_7__pxrReserved__::(anonymous namespace)::_ClipSet::_AnchorInfo>'
    optional& operator= ( optional && rhs )
              ^
/usr/local/include/boost/optional/optional.hpp:994:15: note: candidate function not viable: cannot convert initializer list argument to 'boost::none_t'
    optional& operator= ( none_t none_ ) BOOST_NOEXCEPT
              ^
/usr/local/include/boost/optional/optional.hpp:902:5: note: candidate template ignored: couldn't infer template argument 'Expr'
    operator= ( Expr&& expr )
    ^
/usr/local/include/boost/optional/optional.hpp:922:15: note: candidate template ignored: couldn't infer template argument 'U'
    optional& operator= ( optional<U> const& rhs )
              ^
/usr/local/include/boost/optional/optional.hpp:933:15: note: candidate template ignored: couldn't infer template argument 'U'
    optional& operator= ( optional<U> && rhs )
              ^
/usr/local/include/boost/optional/optional.hpp:964:5: note: candidate template ignored: couldn't infer template argument 'T_'
    operator= ( T_&& val )
    ^
```

I can fix it with this patch, which I didn't like much:

```diff
diff --git a/pxr/usd/lib/usd/clip.cpp b/pxr/usd/lib/usd/clip.cpp
index 0bfb8a37..b3c652f4 100644
--- a/pxr/usd/lib/usd/clip.cpp
+++ b/pxr/usd/lib/usd/clip.cpp
@@ -569,7 +569,7 @@ _RecordAnchorInfo(
         const SdfPath& path = node.GetPath();
         const PcpLayerStackRefPtr& layerStack = node.GetLayerStack();
         const SdfLayerRefPtr& layer = layerStack->GetLayers()[layerIdx];
-        clipSet->anchorInfo = {
+        clipSet->anchorInfo = (_ClipSet::_AnchorInfo) {
             layerStack, path, layerIdx, 0, // This will get filled in later
             _GetLayerOffsetToRoot(node, layer)
         };
```

### System Information (OS, Hardware)

I'm building on macOS 10.12.5 with current Xcode (clang version is `Apple LLVM version 8.1.0 (clang-802.0.42)`).

**Comment by jtran56** [comment]
Filed as internal issue #148982.
