### ISSUE TITLE
Error while compiling USD for Katana3.1v5

### ISSUE THREAD

**Issue by gshankar165** [PixarAnimationStudios/USD#947]
### Steps to Reproduce
1.

**Comment by gshankar165** [comment]
I am trying to compile using below command for Katana3.1v5. I have below error.

**Description of Issue**
usr/local/USD/USD-master/third_party/katana/lib/usdKatana/utils.cpp:52:28: fatal error: vtKatana/array.h: No such file or directory
 #include "vtKatana/array.h"
                            ^
compilation terminated.
gmake[2]: *** Waiting for unfinished jobs....
Linking CXX shared library _usdAppUtils.so
[ 97%] Built target _usdAppUtils
gmake[1]: *** [third_party/katana/lib/usdKatana/CMakeFiles/usdKatana.dir/all] Error 2
gmake: *** [all] Error 2

**System Information (OS, Hardware)**
CentOS Linux release 7.6.1810 ,
Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
kernel: 5.0.5-1.el7.elrepo.x86_64

**Build Flags**
python /usr/local/USD/USD-master/build_scripts/build_usd.py --katana --katana-api-location /opt/Katana3.1v5 /usr/local/USD

**Comment by radon199** [comment]
array.h is a file that comes with USD, not Katana. It is found at : third_party/Katana/vtKatana/array.h

Do you see this file in your USD download? I can see it in the github repo so I would suggest re-downloading USD from Github and see if it works.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5516

**Comment by gshankar165** [comment]
yes it is working now after redownloading the zip.
