### ISSUE TITLE
Linking errors for molithic build with TBB and latest v25.05

### ISSUE THREAD

**Issue by marcodiiga** [PixarAnimationStudios/USD#3628]
Hello, since latest `v25.05` I've been getting undefined linking errors related to TBB (is oneTBB supposed to replace TBB now? but that also doesn't work) when using `--build-monolithic`, full command:

```
python deps/OpenUSD/build_scripts/build_usd.py --no-python --build-monolithic --build-variant release ./build/deps/OpenUSD
```

without `--build-monolithic` everything works. Since I'm trying to generate a statically linked small executable, any idea if this is a regression?

```
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_push_back(unsigned long, unsigned long&)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::deallocate_via_handler_v3(void*)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::free(tbb::task&) const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::task_group_context::init()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_additional_child_of_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::get_initial_auto_partitioner_divisor()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::task_group_context::~task_group_context()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::spin_rw_mutex_v3::internal_acquire_reader()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_additional_child_of_proxy::free(tbb::task&) const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_via_handler_v3(unsigned long)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::spin_rw_mutex_v3::internal_try_acquire_writer()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::NFS_Free(void*)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::task_group_context::is_group_execution_cancelled() const'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::spin_rw_mutex_v3::internal_upgrade()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::concurrent_vector_base_v3::~concurrent_vector_base_v3()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_clear(void (*)(void*, unsigned long))'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::spin_rw_mutex_v3::internal_acquire_writer()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_resize(unsigned long, unsigned long, unsigned long, void const*, void (*)(void*, unsigned long), void (*)(void*, void const*, unsigned long))'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::thread_get_id_v3()'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_grow_by(unsigned long, unsigned long, void (*)(void*, void const*, unsigned long), void const*)'
/usr/bin/ld: ../../../../libusd_ms.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const'
collect2: error: ld returned 1 exit status
```

I'm using g++ 13.3.0 on Ubuntu 24.04.

**Comment by marcodiiga** [comment]
Worth noting that this is also happening with a clean checkout of ToT (88b61f08e091d40312b6ce14d9c14b4a342b3e6f right now) - lots of TBB-related errors
```
/tmp/OpenUSD$ python build_scripts/build_usd.py --no-python --build-monolithic ./build
```
still seems `--build-monolithic` might trigger this

**Comment by sunyab** [comment]
Hi @marcodiiga , I'm unable to reproduce this on my Linux machine. Could you post the build log from `./build/OpenUSD/log.txt` as well as `./build/OpenUSD/CMakeCache.txt`?

Also, it looks like you're building into a subdirectory beneath the OpenUSD repo itself. In the past I've found that can cause linker issues -- could you try building into a directory outside of the OpenUSD repo?

**Comment by marcodiiga** [comment]
Closing this down, after a more careful examination it's picking up the system (incompatible) TBB, something already reported: https://github.com/PixarAnimationStudios/OpenUSD/issues/3610#issue-3013334330

Thanks for checking anyway!
