### ISSUE TITLE
M1 Macbook: Error when running usdview command

### ISSUE THREAD

**Issue by leo-luo-lzy** [PixarAnimationStudios/USD#2483]
### System Information (MacOS, M1pro)
###Python 3.11

Command:
$ ls
CMakeLists.txt	Sphere.usd	Sphere.usda
$ usdview Sphere.usda

Feedback:
Warning: in Tf_PyLoadScriptModule at line 117 of /Users/macbook/Documents/GitHub/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.Usd'!
Traceback (most recent call last):
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usd/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
Warning: in Tf_PyLoadScriptModule at line 117 of /Users/macbook/Documents/GitHub/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.UsdGeom'!
Traceback (most recent call last):
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/UsdGeom/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No to_python (by-value) converter found for C++ type: pxrInternal_v0_23__pxrReserved__::UsdTimeCode
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdListPosition> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdListPosition already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomBBoxCache already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomConstraintTarget already registered; second conversion method ignored.
State file not found, a new one will be created.
Traceback (most recent call last):
  File "/Users/macbook/Documents/PixarUSD/bin/usdview", line 35, in <module>
    Usdviewq.Launcher().Run()
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/__init__.py", line 86, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/__init__.py", line 396, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/__init__.py", line 386, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/appController.py", line 410, in __init__
    self._dataModel = UsdviewDataModel(self._makeTimer, self._configManager.settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/appController.py", line 128, in __init__
    self._viewSettingsDataModel = ViewSettingsDataModel(self, settings)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/PixarUSD/lib/python/pxr/Usdviewq/viewSettingsDataModel.py", line 136, in __init__
    QtCore.QObject.__init__(self)
TypeError: StateSource.__init__() missing 2 required positional arguments: 'parent' and 'name'

**Comment by dinelanthony** [comment]
This was an issue I had, and the fix in #2407 fixed it. As mentioned it is because of PySide6, so you could alternatively downgrade to PySide2

**Comment by leo-luo-lzy** [comment]
> This was an issue I had, and the fix in #2407 fixed it. As mentioned it is because of PySide6, so you could alternatively downgrade to PySide2

Thank you very much!

**Comment by leo-luo-lzy** [comment]
[log.txt](https://github.com/PixarAnimationStudios/USD/files/11691222/log.txt)
It comes an another issue when I use pyside2, as can be seen in the log. Is it related to the python version? Should I also downgrade the python version?

**Comment by dinelanthony** [comment]
USD isn't yet optimized for the latest Python release. I know others have gotten 3.10 working but I didn't have that luck. I personally have it working with 3.9.13 so if your project doesn't necessarily require 3.11 I would recommend downgrading to 3.9.13. Just remember to update your user PATH and PYTHONPATH so that the 3.9 installation is above the 3.11 installation or you will continue to have the same issue

for reference I have:

PySide6
Python 3.9.13

**Comment by leo-luo-lzy** [comment]
Hello, I have the similar problem as Issue #1979 now. But I still cannot solve the problems after following the guidance in that issue.

PySide6
Python 3.9.6
cmake 3.26.4
System Information (MacOS, M1pro)

Command:
$ file \`which cmake\`
/Users/macbook/Library/Python/3.9/lib/python/site-packages/cmake/data/bin/cmake: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/Users/macbook/Library/Python/3.9/lib/python/site-packages/cmake/data/bin/cmake (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/macbook/Library/Python/3.9/lib/python/site-packages/cmake/data/bin/cmake (for architecture arm64):	Mach-O 64-bit executable arm64

[log.txt](https://github.com/PixarAnimationStudios/USD/files/11692105/log.txt)

**Comment by Prachitbooks** [comment]
I am facing similar problem.

Python 3.9.13
Pyside6 
cmake  3.25.1
System - Linux 

[log.txt](https://github.com/PixarAnimationStudios/USD/files/11692811/log.txt)

**Comment by meshula** [comment]
@leo-luo-lzy I'm not sure why, but it looks like there's an issue with tbb, your build didn't complete.

```
[ 33%] Linking CXX shared library libusd_tf.dylib
Undefined symbols for architecture arm64:
  "tbb::detail::r1::allocate_memory(unsigned long)", referenced from:
      pxrInternal_v0_23__pxrReserved__::Tf_NoticeRegistry::Tf_NoticeRegistry() in noticeRegistry.cpp.o
      tbb::detail::d1::callback_leaf<tbb::detail::d1::construct_by_default<unsigned long>>::clone() const in noticeRegistry.cpp.o
      pxrInternal_v0_23__pxrReserved__::TfDiagnosticMgr::TfDiagnosticMgr() in diagnosticMgr.cpp.o
      tbb::detail::d1::callback_leaf<tbb::detail::d1::construct_by_exemplar<unsigned long>>::clone() const in diagnosticMgr.cpp.o
      tbb::detail::d1::callback_leaf<tbb::detail::d1::construct_by_default<bool>>::clone() const in diagnosticMgr.cpp.o
      tbb::detail::d1::callback_leaf<tbb::detail::d1::construct_by_default<std::__1::list<pxrInternal_v0_23__pxrReserved__::TfError, std::__1::allocator<pxrInternal_v0_23__pxrReserved__::TfError>>>>::clone() const in diagnosticMgr.cpp.o
      tbb::detail::d1::callback_leaf<tbb::detail::d1::construct_by_default<pxrInternal_v0_23__pxrReserved__::TfDiagnosticMgr::_LogText>>::clone() const in diagnosticMgr.cpp.o
      ...
            tbb::detail::d1::enumerable_thread_specific<unsigned long, tbb::detail::d1::cache_aligned_allocator<unsigned long>, (tbb::detail::d1::ets_key_usage_type)0>::free_array(void*, unsigned long) in diagnosticMgr.cpp.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pxr/base/tf/libusd_tf.dylib] Error 1
make[1]: *** [pxr/base/tf/CMakeFiles/tf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by meshula** [comment]
@Prachitbooks once again, I don't know why it happened, but your build has failed for a different reason, it can't link Python itself.

```
...
/usr/bin/ld: /usr/local/google/home/prachitraorane/Downloads/USD/lib/libboost_python39.so: undefined reference to `PyUnicode_AsUTF8String'
/usr/bin/ld: ../../sdf/libusd_sdf.so: undefined reference to `PyUnicode_FromStringAndSize'
/usr/bin/ld: /usr/local/google/home/prachitraorane/Downloads/USD/lib/libboost_python39.so: undefined reference to `PyDict_Clear'
/usr/bin/ld: /usr/local/google/home/prachitraorane/Downloads/USD/lib/libboost_python39.so: undefined reference to `PyNumber_InPlaceLshift'
/usr/bin/ld: ../../sdf/libusd_sdf.so: undefined reference to `PyBool_FromLong'
/usr/bin/ld: /usr/local/google/home/prachitraorane/Downloads/USD/lib/libboost_python39.so: undefined reference to `PyNumber_InPlaceAdd'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8413
