### PR TITLE
Enable Python 3.11 builds with Boost 1.82

### PR DESCRIPTION
**Pull request by dgovil**
### Description of Change(s)

This PR resolves https://github.com/PixarAnimationStudios/OpenUSD/issues/2741 by using Boost 1.82 for Python 3.11 or above, in accordance with VFX Platform CY2024.

### Fixes Issue(s)
https://github.com/PixarAnimationStudios/OpenUSD/issues/2741

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8843

**Comment by sunyab** [comment]
@dgovil Hey Dhruv, I'm looking at merging this in but I'm running into issues building OpenImageIO on my Linux machine with this change. I get a bunch of undefined reference errors with boost::filesystem, like below. Do you see anything similar on your machine?

```
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::extension() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::root_directory() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::parent_path() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::replace_extension(boost::filesystem::path const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::filename() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../lib/libOpenImageIO_Util.so.2.3.21: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
```

**Comment by dgovil** [comment]
Oh interesting. I must have built without OIIO. I'll check that out today and get back to you

**Comment by dgovil** [comment]
Still looking for OIIO, but I was hitting an issue when I updated my Toolchain and Boost's fallback to C++03 was using deprecated symbols. I've set Boost to Cxx17 on macOS, though I think at some point we should do that across the board? I don't have a Win/Linux build setup to test if they also need 17 or not.

**Comment by dgovil** [comment]
@sunyab , at least on macOS with Clang 15, I'm not getting a compile error with OIIO. I did have to make a change to Boost for macOS to use C++17 and I wonder if adding those cxxflags to Linux as well would fix things for you?

**Comment by sunyab** [comment]
I was able to get past my issue by updating my version of CMake to latest. I was running 3.25.3 which didn't have explicit support for boost 1.82. 

So what I'd propose is:
- File a separate PR for the boost C++17 changes.

- For this PR, let's go back to what you had originally, but also add a check for CMake version here so that users are required to have 3.27 or above in this case: https://github.com/PixarAnimationStudios/OpenUSD/blob/0b18ad3f840c24eb25e16b795a5b0821cf05126e/build_scripts/build_usd.py#L2275

If you'd like, I'd be happy to take this off your plate and make these changes locally since I'm already in the middle of testing builds anyway. What do you think?

**Comment by dgovil** [comment]
Ah interesting. Yeah, if you're already in there, it's probably faster if you do it since I won't be able to adequately test Linux. Thank you!

Split out the CXX17 PR here https://github.com/PixarAnimationStudios/OpenUSD/pull/2868

**Comment by sunyab** [comment]
I've checked in an updated version of this PR internally and it'll go out with the next updates to the dev branch. Closing this out, thanks!

**Comment by dgovil** [comment]
Thanks, Sunya!
