### ISSUE TITLE
Does not build with MaterialX 1.38.6

### ISSUE THREAD

**Issue by lpapp** [PixarAnimationStudios/USD#2216]
I am trying to use MaterialX 1.38.6 and getting this:

pxr/usd/usdMtlx/reader.h:31:10: fatal error: 'MaterialXCore/Document.h' file not found
#include <MaterialXCore/Document.h>

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7946

**Comment by FlorianZ** [comment]
@lpapp we are currently building with MaterialX 1.38.4. My guess is that this header was relocated/removed with a newer version of MaterialX, as weird as that would be for a minor version bump. You could visit the USD MaterialX ASWF slack channel for expert help.

If you end up figuring this out, we welcome a contribution as always. Thank you!!

**Comment by JGamache-autodesk** [comment]
You can try merging [Pablo's update to MaterialX 1.38.5](https://github.com/PixarAnimationStudios/USD/pull/1965), and since 1.38.6 does not contain any change that breaks the API USD is using, it should work out of the box.
