### ISSUE TITLE
usdAbc does not compile with Alembic 1.7

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#106]
/Users/asluk/Desktop/bin/usd-dev/USD/pxr/usd/plugin/usdAbc/alembicWriter.cpp:2410:34: error: no matching constructor for
      initialization of 'Alembic::Abc::v9::OObject'
    shared_ptr<OObject> root(new OObject(context->GetArchive(), kTop));
                                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/pxr/usd/plugin/usdAbc/alembicWriter.cpp:35:
/Users/asluk/Desktop/bin/abc-dev/install/include/Alembic/Abc/OObject.h:120:5: note: candidate constructor not viable: 1st
      argument ('const Alembic::Abc::v9::OArchive') would lose const qualifier
    OObject( OArchive & iArchive,
    ^

This seems to be triggered by this change in Alembic - https://github.com/alembic/alembic/commit/18f56e1b83119290aa1938ba9936dc291fbdda4a#diff-8ad0a083ad55a6cd81c3a5b38b876360

but I'm not sure why the code currently compiles in Alembic versions < 1.7, as it doesn't seem to be const-correct wrto the call OArchive::getTop at, for example, https://github.com/alembic/alembic/blob/1.5.8/lib/Alembic/Abc/OObject.h#L120

I verified that const_cast'ing GetArchive() result at https://github.com/PixarAnimationStudios/USD/blob/e6ce9e884a65e7d6acd762e9dbc961dcf9aa36bb/pxr/usd/plugin/usdAbc/alembicWriter.cpp#L2412 fixes the build, and that I can read and write Abc files properly with the resultant build, but defer to the Pixar admins as to whether they'd want to propagate the proper non-const use of the OArchive down through the other helper classes in usdAbc/alembicWriter.cpp

Here's my change, FWIW - https://github.com/asluk/USD/commit/db24ba194ebc42349a48ede56aba5e9f7a07e4fd

**Comment by meshula** [comment]
usd-build-club pins Alembic at version 1.6.1 to avoid the problem. I too would like to see a fix such as your proposed asluk@db24ba1

**Comment by jtran56** [comment]
Filed as internal issue #140234.

**Comment by sunyab** [comment]
This fix was merged into release 0.7.3.
