### ISSUE TITLE
usdMaya build failure on OSX

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/USD#162]
### Description of Issue
The usdMaya plugin fails to build on OSX in 0.7.3 with an error like:

third_party/maya/lib/usdMaya/shadingModeDisplayColor.cpp:191:1: error: redefinition of 'arch_ctor__Tf_RegistryAdddisplayColor'

This may have been introduced with commit 30194385, though we haven't confirmed this yet.

(Note that OSX support in USD is still experimental at this time.)

### Steps to Reproduce
1. Attempt to build the usdMaya plugin on OSX.

### System Information (OS, Hardware)
OSX

**Comment by jtran56** [comment]
Filed as internal issue #142892.
