### ISSUE TITLE
build fail on linux cluster

### ISSUE THREAD

**Issue by uturuncoglu** [PixarAnimationStudios/USD#2047]
### Description of Issue
I am trying to build the USD under a linux cluster and it fails with following error,

```
ERROR: Failed to run './b2 --prefix="/glade/scratch/turuncu/IDEAS/progs/usd-22.08/install" --build-dir="/glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/build" -j64 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-program_options --with-regex --with-python --user-config=python-config.jam install'
See /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/src/boost_1_70_0/log.txt for more details.
```

there is no any valuable information that could help to solve the issue.

### Steps to Reproduce
1. wget https://github.com/PixarAnimationStudios/USD/archive/refs/tags/v22.08.tar.gz
2. tar -zxvf v22.08.tar.gz
3. mv USD-22.08 usd-22.08
4. rm v22.08.tar.gz
5. cd usd-22.08
6. mkdir install
7. module load python cmake
8. conda update -n base -c defaults conda
9. conda create --prefix /glade/scratch/turuncu/IDEAS/progs/conda-usd
10. conda activate /glade/scratch/turuncu/IDEAS/progs/conda-usd
11. conda install PyOpenGL
12. conda config --add channels conda-forge
13. conda config --set channel_priority strict 
14. conda install PySide2
15. python build_scripts/build_usd.py install

### System Information (OS, Hardware)
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 4

and using one of the node (Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz)

### Package Versions
v22.08

### Build Flags
```
Building with settings:
  USD source directory          /glade/scratch/turuncu/IDEAS/progs/usd-22.08
  USD install directory         /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install
  3rd-party source directory    /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/src
  3rd-party install directory   /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install
  Build directory               /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Variant                     Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      Off 
      OpenColorIO support:      Off 
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python Debug:             Off
      Python 3:                 On
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  boost, TBB, OpenSubdiv
```

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7644

**Comment by uturuncoglu** [comment]
@tallytalwar Thanks for the information and help. Is there any option that I could try. I don't need to use the latest version. Do you think using previous versions could help?

**Comment by meshula** [comment]
@uturuncoglu could you attach /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/src/boost_1_70_0/log.txt ? It's hard to guess what the issue is without the extra diagnostic output.

**Comment by uturuncoglu** [comment]
@meshula here is the log file - [log.txt](https://github.com/PixarAnimationStudios/USD/files/9604054/log.txt). let me know if you need any other information. Thanks.

**Comment by meshula** [comment]
Hi, that's very helpful. You have hit an incompatibility between Python 3.10 and the version of boost::python being installed by build_usd.py. I found the following in log.txt:

```
libs/python/src/exec.cpp: In function ‘boost::python::api::object boost::python::exec_file(const char*, boost::python::api::object, boost::python::api::object)’:
libs/python/src/exec.cpp:109:30: error: ‘_Py_fopen’ was not declared in this scope
   FILE *fs = _Py_fopen(f, "r");
```
It was fixed here: https://github.com/boostorg/python/pull/344 

If you open build_usd.py, and search for BOOST_URL, please change the version from 1.76.0 to 1.78.0, and I believe you'll be able to build.

This PR https://github.com/PixarAnimationStudios/USD/pull/2007 updates boost version for python 3.10 compatibility ~ please monitor it for updates.

**Comment by uturuncoglu** [comment]
@meshula Thanks for your help. In my case I am installing under Linux and here the line in the build script.

```
    BOOST_URL = "https://boostorg.jfrog.io/artifactory/main/release/1.70.0/source/boost_1_70_0.tar.gz"
    BOOST_VERSION_FILE = "include/boost/version.hpp"
```

So, I need to update from 1.70 to 1.78. Right?

**Comment by meshula** [comment]
To my knowledge, 1.78 is the minimum necessary for Python 3.10. I don't know if there are other Python 3.10 related issues that you will encounter, but I do think it is worth trying to bump the version, and letting us know what happens.

At the moment, USD is tracking vfxplatform 2020, which means things are not yet testing against 3.10. see ~ https://vfxplatform.com

**Comment by uturuncoglu** [comment]
@meshula Thanks. I tried with 1.78 and it gone further but end up with following error,

```
icpc -E -x c++ ../../src/tbb/lin64-tbb-export.def -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m64   -fPIC  -D__TBB_BUILD=1 -Wall -Wno-parentheses  -I../../src -I../../src/rml/include -I../../include > tbb.def
icpc -o tbb_misc.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m64   -fPIC  -D__TBB_BUILD=1 -Wall -Wno-parentheses    -I../../src -I../../src/rml/include -I../../include -I. ../../src/tbb/tbb_misc.cpp
In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1221): error: expected a declaration
  using hash_map_t = Map<
  ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1221): error: expected a ";"
  using hash_map_t = Map<
  ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1227): warning #12: parsing restarts here after previous syntax error
  >;
   ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1232): error: argument list for class template "tbb::interface5::concurrent_hash_map" is missing
  concurrent_hash_map(I, I, Args...)
  ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1232): error: expected a ")"
  concurrent_hash_map(I, I, Args...)
                       ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1232): error: "I" is not a function or static data member
  concurrent_hash_map(I, I, Args...)
                      ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1238): error: argument list for class template "tbb::interface5::concurrent_hash_map" is missing
  concurrent_hash_map(std::initializer_list<std::pair<const Key, T>>, CompareOrAllocator)
  ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1238): error: namespace "std" has no member "initializer_list"
  concurrent_hash_map(std::initializer_list<std::pair<const Key, T>>, CompareOrAllocator)
                           ^

In file included from ../../src/tbb/concurrent_hash_map.cpp(17):
../../include/tbb/concurrent_hash_map.h(1238): error: expected a ")"
  concurrent_hash_map(std::initializer_list<std::pair<const Key, T>>, CompareOrAllocator)
                                           ^

compilation aborted for ../../src/tbb/concurrent_hash_map.cpp (code 2)
../../build/common_rules.inc:76: recipe for target 'concurrent_hash_map.o' failed
make[1]: *** [concurrent_hash_map.o] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1163): error: argument list for class template "tbb::concurrent_vector" is missing
  > concurrent_vector(I, I, const A& = A())
    ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1163): error: expected a ")"
  > concurrent_vector(I, I, const A& = A())
                       ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1163): error: "I" is not a function or static data member
  > concurrent_vector(I, I, const A& = A())
                      ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1168): error: argument list for class template "tbb::concurrent_vector" is missing
  concurrent_vector(const concurrent_vector<T, A1> &, const A2 &)
  ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1168): warning #945: type qualifier ignored
  concurrent_vector(const concurrent_vector<T, A1> &, const A2 &)
                    ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1168): error: an explicit template argument list is not allowed on this declaration
  concurrent_vector(const concurrent_vector<T, A1> &, const A2 &)
                          ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1168): error: expected a ")"
  concurrent_vector(const concurrent_vector<T, A1> &, const A2 &)
                                                   ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1173): error: argument list for class template "tbb::concurrent_vector" is missing
  > concurrent_vector(std::initializer_list<T>, const A& = A())
    ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1173): error: namespace "std" has no member "initializer_list"
  > concurrent_vector(std::initializer_list<T>, const A& = A())
                           ^

In file included from ../../src/tbb/concurrent_vector.cpp(23):
../../include/tbb/concurrent_vector.h(1173): error: expected a ")"
  > concurrent_vector(std::initializer_list<T>, const A& = A())
                                           ^

compilation aborted for ../../src/tbb/concurrent_vector.cpp (code 2)
../../build/common_rules.inc:76: recipe for target 'concurrent_vector.o' failed
make[1]: *** [concurrent_vector.o] Error 2
make[1]: Leaving directory '/glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/src/oneTBB-2019_U6/build/linux_intel64_gcc_cc4.8_libc2.22_kernel4.12.14_debug'
Makefile:28: recipe for target 'tbb' failed
make: *** [tbb] Error 2

ERROR: Failed to run 'make -j72 '
```

**Comment by meshula** [comment]
I dug into the log.txt you posted, and I see references such as this `gcc-4.8`. Referring again to vfxplatform cy2020, the oldest gcc that we are testing and building with at the moment is gcc 6.3.1. Have you got 6.3.1 or a more recent gcc available to use? Unfortunately we no longer hold development back to earlier compilers.

**Comment by uturuncoglu** [comment]
@meshula I could use newer version of gcc since I have following versions in the system,

gnu/7.4.0
gnu/8.3.0
gnu/9.1.0    
gnu/10.1.0 (D)
gnu/11.1.0
gnu/11.2.0
gnu/12.1.0

I think it picks the default one shipped with the OS since I load the Intel compiler. BTW, is it also possible to use intel compiler? Anyway, let me test it with another gcc first.

**Comment by uturuncoglu** [comment]
@meshula I loaded newer version of gcc (gnu/10.1.0) and have fresh install after updating BOOST_URL to 1.78.0. It went further and failed like following,

```
[ 34%] Building CXX object pxr/base/tf/CMakeFiles/tf.dir/wrapTypeHelpers.cpp.o
In file included from /glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/token.cpp:32:
/glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/instantiateSingleton.h: In instantiation of ‘static T& pxrInternal_v0_22__pxrReserved__::TfSingleton<T>::_CreateInstance() [with T = pxrInternal_v0_22__pxrReserved__::Tf_TokenRegistry]’:
/glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/token.cpp:264:1:   required from here
/glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/instantiateSingleton.h:71:19: warning: ‘new’ of type ‘pxrInternal_v0_22__pxrReserved__::Tf_TokenRegistry’ with extended alignment 64 [-Waligned-new=]
   71 |         T *inst = new T;
      |                   ^~~~~
/glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/instantiateSingleton.h:71:19: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/glade/scratch/turuncu/IDEAS/progs/usd-22.08/pxr/base/tf/instantiateSingleton.h:71:19: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
CMakeFiles/Makefile2:2632: recipe for target 'pxr/base/tf/CMakeFiles/tf.dir/all' failed
gmake[1]: *** [pxr/base/tf/CMakeFiles/tf.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
gmake: *** [all] Error 2

ERROR: Failed to run 'cmake --build . --config Release --target install -- -j72'
See /glade/scratch/turuncu/IDEAS/progs/usd-22.08/install/build/usd-22.08/log.txt for more details.
```

I could confirm that build used 10.1.0. See following part from the log,

```
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing OpenSubdiv...
STATUS: Installing USD...
2022-09-20 22:36
cmake -DCMAKE_INSTALL_PREFIX="/glade/scratch/turuncu/IDEAS/progs/usd-22.08/install" -DCMAKE_PREFIX_PATH="/glade/scratch/turuncu/IDEAS/progs/usd-22.08/install" -DCMAKE_BUILD_TYPE=Release    -DPXR_PREFER_SAFETY_OVER_SPEED=ON -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPXR_USE_PYTHON_3=ON -DPXR_USE_DEBUG_PYTHON=OFF -DPYTHON_EXECUTABLE="/glade/scratch/turuncu/IDEAS/progs/conda-usd/bin/python" -DPYTHON_LIBRARY="/glade/scratch/turuncu/IDEAS/progs/conda-usd/lib/libpython3.10.a" -DPYTHON_INCLUDE_DIR="/glade/scratch/turuncu/IDEAS/progs/conda-usd/include/python3.10" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_USD_TOOLS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_ENABLE_MATERIALX_SUPPORT=OFF -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "/glade/scratch/turuncu/IDEAS/progs/usd-22.08"
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
```

Anyway, I'll try to install with `gnu/11.2.0`to see what happens.

**Comment by gitamohr** [comment]
There is a fix for that specific error in the dev branch (has not made it to release yet).  But like @meshula says, your best bet is to use versions as close to those in the vfx reference platform CY2020 (https://vfxplatform.com/) as you can.  That means gcc 6.3.1, python 3.7.x, boost 1.70, TBB 2019 update 6, among others.  This is the software set we are building, testing, and running against the most.

**Comment by jiapei100** [comment]
Same here:

```
[ 44%] Built target vt
/usr/bin/c++  -Wall -Wformat-security -pthread -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-maybe-uninitialized  -O3 -DNDEBUG CMakeFiles/testTraceEventContainer.dir/testenv/testTraceEventContainer.cpp.o -o testTraceEventContainer  -Wl,-rpath,....../OpenUSD/build/pxr/base/trace:....../OpenUSD/build/pxr/base/js:....../OpenUSD/build/pxr/base/tf:....../OpenUSD/build/pxr/base/arch: libusd_trace.so ../js/libusd_js.so ../tf/libusd_tf.so ../arch/libusd_arch.so -ldl -lm /usr/lib/x86_64-linux-gnu/libpython3.12.so /usr/lib/x86_64-linux-gnu/libboost_python312.so /usr/lib/x86_64-linux-gnu/libtbb.so
/usr/bin/c++  -Wall -Wformat-security -pthread -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-maybe-uninitialized  -O3 -DNDEBUG CMakeFiles/testTraceSerialization.dir/testenv/testTraceSerialization.cpp.o -o testTraceSerialization  -Wl,-rpath,....../OpenUSD/build/pxr/base/trace:....../OpenUSD/build/pxr/base/js:....../OpenUSD/build/pxr/base/tf:....../OpenUSD/build/pxr/base/arch: libusd_trace.so ../js/libusd_js.so ../tf/libusd_tf.so ../arch/libusd_arch.so -ldl -lm /usr/lib/x86_64-linux-gnu/libpython3.12.so /usr/lib/x86_64-linux-gnu/libboost_python312.so /usr/lib/x86_64-linux-gnu/libtbb.so
/usr/bin/c++  -Wall -Wformat-security -pthread -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-maybe-uninitialized  -O3 -DNDEBUG CMakeFiles/testTraceCounters.dir/testenv/testTraceCounters.cpp.o -o testTraceCounters  -Wl,-rpath,....../OpenUSD/build/pxr/base/trace:....../OpenUSD/build/pxr/base/js:....../OpenUSD/build/pxr/base/tf:....../OpenUSD/build/pxr/base/arch: libusd_trace.so ../js/libusd_js.so ../tf/libusd_tf.so ../arch/libusd_arch.so -ldl -lm /usr/lib/x86_64-linux-gnu/libpython3.12.so /usr/lib/x86_64-linux-gnu/libboost_python312.so /usr/lib/x86_64-linux-gnu/libtbb.so
/usr/bin/ld: libusd_gf.so: undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfScriptModuleLoader>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfScriptModuleLoader*>&)'
/usr/bin/ld: libusd_gf.so: undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfScriptModuleLoader>::_instance'
collect2: error: ld returned 1 exit status
make[2]: *** [pxr/base/gf/CMakeFiles/testGfHardToReach.dir/build.make:107: pxr/base/gf/testGfHardToReach] Error 1
make[2]: Leaving directory '....../OpenUSD/build'
make[1]: *** [CMakeFiles/Makefile2:3722: pxr/base/gf/CMakeFiles/testGfHardToReach.dir/all] Error 2
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/delegate.cpp.o: in function `pxrInternal_v0_24__pxrReserved__::Test_TfDelegateAddRemove()':
delegate.cpp:(.text+0x22): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_instance'
/usr/bin/ld: delegate.cpp:(.text+0x34c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: delegate.cpp:(.text+0x364): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: delegate.cpp:(.text+0x374): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: delegate.cpp:(.text+0x38c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/delegate.cpp.o: in function `pxrInternal_v0_24__pxrReserved__::Test_TfDelegateAddRemove() [clone .cold]':
delegate.cpp:(.text.unlikely+0x1): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::GetInstance()'
/usr/bin/ld: delegate.cpp:(.text.unlikely+0x35): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::GetInstance()'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/error.cpp.o: in function `pxrInternal_v0_24__pxrReserved__::TfErrorMark::Clear() const [clone .isra.0]':
error.cpp:(.text+0x2ce): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_instance'
/usr/bin/ld: error.cpp:(.text+0x36c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0x37c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/error.cpp.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<Test_TfErrorThreadTransport()::{lambda()#1}> > >::_M_run()':
error.cpp:(.text+0x436): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_instance'
/usr/bin/ld: error.cpp:(.text+0x4ac): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0x5dc): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0x5f4): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0x664): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/error.cpp.o: in function `Test_TfErrorThreadTransport()':
error.cpp:(.text+0x75a): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_instance'
/usr/bin/ld: error.cpp:(.text+0x85c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0x984): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xa34): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xa44): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xa54): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/error.cpp.o: in function `Test_TfError()':
error.cpp:(.text+0xaed): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_instance'
/usr/bin/ld: error.cpp:(.text+0xc54): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xd04): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xf7c): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xf94): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: error.cpp:(.text+0xfa4): undefined reference to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)'
/usr/bin/ld: CMakeFiles/testTf.dir/testenv/error.cpp.o:error.cpp:(.text+0xfb4): more undefined references to `pxrInternal_v0_24__pxrReserved__::TfSingleton<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr>::_CreateInstance(std::atomic<pxrInternal_v0_24__pxrReserved__::TfDiagnosticMgr*>&)' follow
......
```
