### ISSUE TITLE
[usdview] Nothing shown on usdview after build

### ISSUE THREAD

**Issue by raska-s** [PixarAnimationStudios/USD#2153]
### Description of Issue
I built USD while as root in a Python venv. I set the environment variables as stated at the end of the build log. After, I ran the helloWorld.py script to check the installation as directed in  https://graphics.pixar.com/usd/release/tut_helloworld.html.

No errors were thrown when running helloWorld.py but when running `usdview  USD/extras/usd/tutorials/helloWorld/HelloWorld.usda` nothing is visualised on usdview. I am aware I'm meant to see a sphere of some sort. Also, the terminal outputs these errors:

>  raska-s@laptop: $usdview  USD/extras/usd/tutorials/helloWorld/HelloWorld.usda
> Warning: in Link at line 417 of /home/rrs554/Documents/first_year/usd_try/USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to link shader: error: unresolved reference to function `OsdPrimitiveIdBase'
> 
> Warning: in Link at line 417 of /home/rrs554/Documents/first_year/usd_try/USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to link shader: error: unresolved reference to function `OsdPrimitiveIdBase'
> 
> ERROR: Usdview encountered an error while rendering.
> 	Error in 'pxrInternal_v0_22__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 278 in file /home/rrs554/Documents/first_year/usd_try/USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /hello/world.'
> 	Error in 'pxrInternal_v0_22__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 297 in file /home/rrs554/Documents/first_year/usd_try/USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed verification: ' res ' -- Failed to compile with fallback material network'
> 	Error in 'pxrInternal_v0_22__pxrReserved__::HdSt_IndirectDrawBatch::_ExecuteDraw' at line 1116 in file /home/rrs554/Documents/first_year/usd_try/USD/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' program.IsValid() ''

Screenshot of usdview:
![image](https://user-images.githubusercontent.com/75393569/211848697-480c2300-d0e7-4c96-8497-994c484677bb.png)

I have tried visualising other files included in the USD directory, most of the ones did not work except 'USD/extras/usd/examples/usdGeomExamples/basisCurves.usda',. This did not throw any errors, and gives the below:
![image](https://user-images.githubusercontent.com/75393569/211849956-67166367-c529-4f17-9c23-3a5f520bb79a.png)

I have tested this as root and as normal user, as well as within and without the python venv - the problem persists. I might have to rebuild USD, is there a better way than just deleting the USD installation directory? For me this is `/usr/local/USD`.

### Steps to Reproduce
1. Build USD as root and in a Python venv (pip) according to the steps in https://github.com/PixarAnimationStudios/USD 
2. Set environment variables as stated at end of build log: `export PATH=$PATH:/usr/local/USD/bin `and `export PYTHONPATH=$PYTHONPATH:/usr/local/USD/lib/python`
3. Run `python3 USD/extras/usd/tutorials/helloWorld/helloWorld.py`
4. Run `usdview USD/extras/usd/tutorials/helloWorld/HelloWorld.usda`

### System Information (OS, Hardware)
OS: Ubuntu 20.04.5 LTS (Focal)
CPU: Intel® Core™ i5-8265U CPU @ 1.60GHz × 8
Graphics: Mesa Intel® UHD Graphics 620 (WHL GT2)
Memory: 15.4 GiB

### Package Versions
Python version: 3.8.10
USD version: [Merge release v22.11](https://github.com/PixarAnimationStudios/USD/commit/0c7b9a95f155c221ff7df9270a39a52e3b23af8b)

### Build Flags

> Building with settings:
>   USD source directory          /home/rrs554/Documents/first_year/usd_try/USD
>   USD install directory         /usr/local/USD
>   3rd-party source directory    /usr/local/USD/src
>   3rd-party install directory   /usr/local/USD
>   Build directory               /usr/local/USD/build
>   CMake generator               Default
>   CMake toolset                 Default
>   Downloader                    curl
> 
>   Building                      Shared libraries
>     Variant                     Release
>     Target                      
>     Imaging                     On
>       Ptex support:             Off
>       OpenVDB support:          Off
>       OpenImageIO support:      Off 
>       OpenColorIO support:      Off 
>       PRMan support:            Off
>     UsdImaging                  On
>       usdview:                  On
>     Python support              On
>       Python Debug:             Off
>       Python 3:                 On
>     Documentation               Off
>     Tests                       Off
>     Examples                    On
>     Tutorials                   On
>     Tools                       On
>     Alembic Plugin              Off
>       HDF5 support:             Off
>     Draco Plugin                Off
>     MaterialX Plugin            Off
> 
>   Dependencies                  boost, TBB, OpenSubdiv

**Comment by LucaScheller** [comment]
Hey @raska-s,

I've been running into the same issue. I guess it is realted to your GPU driver/OpenGL support.
The problem for me was that I had to enforce running on the dedicated GPU. This solved it for me (I have an Nvidia GPU):
```
export __NV_PRIME_RENDER_OFFLOAD=1
export  __GLX_VENDOR_LIBRARY_NAME=nvidia 
usdview USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda
```
Not sure if it is the same problem, but it might be worth looking into though.
Since you have a Intel GPU you'll have to find out how to configure it to force run on the GPU.

I still get this error:
`ERROR: Usdview encountered an error while rendering.Attempt to retrieve context when no valid context`
These are OpenGL errors coming from the drawAxis/drawHud methods. (Probably because I'm running a differen PyOpenGL version)

Cheers,
Luca

**Comment by sunyab** [comment]
Filed as internal issue #USD-7866

**Comment by FlorianZ** [comment]
Thanks for your help @LucaScheller. @raska-s, does this workaround apply to you? Are you still running into this issue? Thanks everyone!

**Comment by isharma25** [comment]
OsdPrimitiveIdbase() function and a few others exist only as function declaration in the file glslPatchCommon.glsl in OpenSubdiv. Adding definitions for these functions(I added temporary/dummy definitions in the same file) seems to resolve these issues. Storm glsl shaders seems to be missing these definitions so either it should be defined within HdSt or provided by OpenSubdiv.

**Comment by davidgyu** [comment]
We've improved this behavior in recent OSD and USD releases to be more compatible with various GLSL shader compilers by removing non-conformant interpolation qualifiers and adding definitions for these previously undefined functions.

Would you be able to try this again using USD v23.02?

Thanks!

**Comment by raska-s** [comment]
Hi, thanks for this. I'll try this again using USD 23.02.

**Comment by carsonbrownlee** [comment]
23.02 exhibits the same behavior for me.  I see there is a runtime defined shader in hdSt/codeGen.cpp whith the missing definitions, however I get errors shown below with unmodified USD build.  This is fixed by explicitly adding the definitions inside of opensubd and removing centroid in glslPatchCommon.glsl.  The isValid error appears in both cases, but does not make any noticeable difference in runtime.  

```
`
Traceback (most recent call last):
  File "/home/cbrownle/git/build-usd-22_03/lib/python/pxr/Usdviewq/stageView.py", line 2436, in _primSelectionChanged
    self.updateSelection()
  File "/home/cbrownle/git/build-usd-22_03/lib/python/pxr/Usdviewq/stageView.py", line 1367, in updateSelection
    renderer = self._getRenderer()
  File "/home/cbrownle/git/build-usd-22_03/lib/python/pxr/Usdviewq/stageView.py", line 950, in _getRenderer
    if self.context().isValid():
AttributeError: 'NoneType' object has no attribute 'isValid'
Warning: in _ValidateCompilation at line 227 of /home/cbrownle/git/USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GEOMETRY_SHADER): 0:1376(2): error: only precision qualifiers may be applied to structure members
0:1377(2): error: only precision qualifiers may be applied to structure members

`

```

**Comment by carsonbrownlee** [comment]
from traces, it looks like in codegen.cpp it never generates the tesselation shaders that add those lines. Could this be related to glsl shader version support, or perhaps the isValid error?  When adding the definitions in osd, everything appears to work fine and the errors go away.

**Comment by davidgyu** [comment]
Thanks for the additional info and testing! Are you building USD v23.02 with OpenSubdiv 3.5.x? That's the version of OpenSubdiv with the non-conformant precision qualifiers removed.
The Traceback from stageView is a separate issue related to using PySide6. We have a separate internal issue open  tracking that.

**Comment by carsonbrownlee** [comment]
edit: yes this was not using updated osd.  rebuilding with 3.5.0 and 23.02 works.

**Comment by carsonbrownlee** [comment]
it works!  my build was mangled. a rebuild with 3.5.0 + 23.02 indeed works without modification with intel drivers on ubutun 22.04.  It is still throwing the context invalid errors, but as you stated that seems to be a separate pyside6 issue.  thanks!

**Comment by davidgyu** [comment]
Excellent! Thank you for the extra testing and verification.

**Comment by tallytalwar** [comment]
Closing this as the pyside6 issue discussed above is fixed with https://github.com/PixarAnimationStudios/USD/commit/067d1ec8c93c32b1a334bed31aedc6d45b5e5dd2
